attributes:
  metadata:
    # Settings group can be one of "general", "security", "compute", "network",
    # "storage", "logging", "openstack_services" and "other".
    group: 'other'
  test_plugin_text:
    value: 'Set default value'
    label: 'Text field'
    description: 'Description for text field'
    weight: 25
    type: "text"
  test_value_input:
    value: 'hehe'
    label: 'It is text field'
    description: 'This is for test text field'
    weight: 25
    type: "text"
  test2_value_input:
    value: false
    label: 'it is checkbox'
    description: 'this is sample check box'
    weight: 30
    type: 'checkbox'

